# Generated by Django 4.0.1 on 2022-01-16 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('hostel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hostel_name', models.CharField(max_length=100)),
                ('vacancy', models.IntegerField(default=0)),
                ('no_of_rooms', models.IntegerField(default=0)),
                ('no_of_students', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100)),
                ('vacancy', models.IntegerField(default=0)),
                ('room_occupancy', models.IntegerField(choices=[(1, 'Single'), (2, 'Double'), (3, 'Triple')])),
                ('room_status', models.CharField(choices=[('OCCUPIED', 1), ('VACANT', 0)], max_length=100)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField()),
                ('dept', models.CharField(max_length=100)),
                ('years_of_study', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Room_allotment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('joining_date', models.DateField()),
                ('vacating_date', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.room')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Hostel_admin',
            fields=[
                ('admin_id', models.IntegerField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField()),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hostel')),
            ],
        ),
    ]
